prometheus:
  url: "http://grafana.soap.com:9090/api/v1/query?query="
  metric: process_virtual_memory_bytes
  threshold: 1173188600
  expr: >-
   container_memory_working_set_bytes{image!="",container=~".*order-.*"}/container_spec_memory_limit_bytes{image!="",container=~".*test"} * 100
  grafanaurl: "http://grafana.soap.com"
    #查询间隔 默认分钟
  window: 5

ding_token: xxxxxxx
secret: xxxx
dingmessage:
  msgtype: "text"
  text: 
    content: "disk alert test \n"
  at:
    isAtAll: false
atalerts:
  eastbuy-bootadmin-service:
  - 1xxxxxxxxxx
