prometheus:
  url: "http://grafana.soap.com:9090/api/v1/query?query="
  metric: process_virtual_memory_bytes
  threshold: 1173188600

dingtalk_webhook: "https://oapi.dingtalk.com/robot/send?access_token=09141823f4ff094ebcb349c8cbdba96ac099aafba21b166131abe0183aadd481"
dingmessage:
  msgtype: "actionCard"
  actionCard: 
    title: "disk alert test"
    text: "@17610862601 \n"
    singleTitle: "消息测试"
    singleURL: "https://grafana.eastbuy.com/d/TCQhwXeVk/pod-disk-info?orgId=1&refresh=1m&from=now-15m&to=now"
  at:
    atMobiles: 
      - 17610862601
    atUserIds: 
      - 杨顺朋
    isAtAll: false
alerts:
  - metric: "up{job=\"kubernetes-pods\"}"
    pod_prefix: "grafana"
    at_user_list:
      - "17610862601"
    threshold: 0.95
    window: 5m
    for: 2m
    every: 10s